name: AI Code Review
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: AI Code Review
        uses: codereview-ai/codereview-ai@v1
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}