# .github/workflows/scrapping.yml

name: Actualizar y Pre-Computar Resultados

on:
  schedule:
    - cron: '0 10 * * 0,3' # Domingo y Miércoles
  workflow_dispatch:

jobs:
  update-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 firebase-admin numpy

      - name: Ejecutar script de scraping
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          APP_ID: ${{ secrets.APP_ID }}
        run: python firebase_scraper.py

      # NUEVO PASO: Ejecutar el script de pre-cómputo después del scraping
      - name: Ejecutar script de pre-cómputo de análisis
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          APP_ID: ${{ secrets.APP_ID }}
        run: python precompute_analysis.py