name: Actualizar Resultados Melate Retro

on:
  schedule:
    # Se ejecuta a las 10:00 AM UTC los domingos y miércoles.
    # Los sorteos de Melate Retro suelen ser los martes y sábados por la noche.
    - cron: '0 10 * * 0,3'
  workflow_dispatch: # Permite la ejecución manual desde la pestaña "Actions" de GitHub

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Puedes usar la versión de Python que prefieras

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 firebase-admin

      - name: Ejecutar script de actualización
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          APP_ID: ${{ secrets.APP_ID }}
        run: python python_firebase_scraper.py # ¡Importante! Reemplaza esto con el nombre real de tu script de Python
